name: Deploy argocd to AKS cluster

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  verify-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check CLIENT_ID secret
        run: echo "CLIENT_ID is set"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

      - name: Check TENANT_ID secret
        run: echo "TENANT_ID is set"
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}

      - name: Check AZURE_SUBSCRIPTION_ID secret
        run: echo "AZURE_SUBSCRIPTION_ID is set"
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check KUBE_CONFIG secret
        run: echo "KUBE_CONFIG is set"
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

#    - name: Login to Azure
#      uses: azure/login@v2
#      with:
#        client-id: ${{ secrets.CLIENT_ID }}
#        tenant-id: ${{ secrets.TENANT_ID }}
#        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#        creds:
#        auth-type: service_principal

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Verify kubectl context
      run: |
        kubectl config view
