name: Deploy NGINX Ingress Controller to AKS

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ingress-controller

jobs:
  deploy-ingress-to-aks:
    runs-on: ubuntu-latest
    environment: aks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          auth-type: service_principal

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: javahelenaResourceGroup
          cluster-name: javahelena-aks

      - name: Verify kubectl access
        run: |
          kubectl config current-context
          kubectl get nodes

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.7.1

      - name: Add NGINX Ingress Helm repo
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update

      - name: Install NGINX Ingress Controller
        run: |
          helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx \
            --namespace ingress-nginx --create-namespace \
            --version 4.11.2 \  # Specify the stable Helm chart version
            --set controller.replicaCount=1 \                                     # Default value is 1
            --set controller.nodeSelector."kubernetes\.io/os"=linux \             # Just for safety. Do not wan to use windows nodes

      - name: Verify NGINX Ingress Controller
        run: |
          kubectl get svc -n ingress-nginx
          kubectl get pods -n ingress-nginx

