name: Deploy argocd to AKS cluster

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - secrets

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    environment: aks

    steps:
      - name: Check CLIENT_ID variable
        run: echo "CLIENT_ID is set"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

      - name: Check CLIENT_SECRET variable
        run: echo "CLIENT_SECRET is set"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_SECRET }}

      - name: Check TENANT_ID variable
        run: echo "TENANT_ID is set"
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}

      - name: Check AZURE_SUBSCRIPTION_ID variable
        run: echo "AZURE_SUBSCRIPTION_ID is set"
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check KUBE_CONFIG secret
        run: echo "KUBE_CONFIG is set"
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
